<?php
	$lang = array(
	'allow_comments' => array(
		'between' => 'Das Kommentare-erlauben-Feld scheint einen ungültigen Wert zu enthalten?',
		'required' => 'Das Kommentare-erlauben-Feld muss ausgefüllt sein.',
	),
	'allow_feed' => array(
		'between' => 'Das Feed-einbinden-Feld scheint einen ungültigen Wert zu enthalten?',
		'required' => 'The Feed-einbinden-Feld muss ausgefüllt sein.',
	),
	'allow_reports' => array(
		'between' => 'Das Berichte-erlauben-Feld scheint einen ungültigen Wert zu enthalten?',
		'required' => 'Das Berichte-erlauben-Feld muss ausgefüllt sein.',
	),
	'allow_stat_sharing' => array(
		'between' => 'Das stat-sharing-Feld scheint einen ungültigen Wert zu enthalten?',
		'required' => 'Das stat-sharing-Feld muss ausgefüllt sein.',
	),
	'api' => array(
		'default_record_limit' => 'Standardanzahl von Einträgen der API-Anforderung',
		'maximum_record_limit' => 'Maximale Anzahl an Einträgen die pro API-Anfrage geholt werden.',
		'maximum_requests_per_ip_address' => 'Maximale Anzahl an API-Anfragen pro IP-Adresse',
	),
	'api_akismet' => array(
		'alpha_numeric' => 'Das Akismet-Feld scheint einen ungültigen Wert zu enthalten?',
		'length' => 'Das Akismet-Feld scheint einen ungültigen Wert zu enthalten?',
	),
	'banner_image' => array(
		'default' => 'Es ist ein Fehler aufgetreten beim Upload deines Bannerbildes.',
		'size' => 'Die Größe deines Banners übertrifft das Größenlimit für diesen Upload.',	
	),
	'api_default_record_limit' => 'Standard API Grenze',
	'cache_pages' => array(
		'between' => 'Das Cache-Feld muss ausgefüllt sein.',
		'required' => 'Das Cache-Feld enthält einen ungültigen Wert',
	),
	'cache_pages_lifetime' => array(
		'in_array' => 'Das Cache-Feld enthält einen ungültigen Wert',
		'required' => 'Das Cache-Feld muss ausgefüllt sein.',
	),
	'cleanurl' => array(
		'clean_url_disabled' => 'Es sieht so aus, als wäre dein Server nicht für den Umgang mit sauberen URLS konfiguriert. Du musst deine Serverkonfiguration anpassen bevor du saubere URLs aktivieren kannst. Weitere Informationen findest du in diesem Forumpost (englisch) <a href="http://forums.ushahidi.com/topic/server-configuration-for-apache-mod-rewrite" target="_blank">post</a>',
		'clean_url_enabled' => 'Mit dieser Option wird Ushahidi über "saubere" URLs erreichbar, ohne "index.php" im URL.',
		'enable_clean_url' => 'Saubere URLs aktivieren',
		'title' => 'Saubere URLs',
	),
	'clickatell_api' => array(
		'length' => 'Das Clickatell-API-Nummern-Feld darf nicht mehr als 20 Zeichen beinhalten.',
		'required' => 'Das Clickatell-API-Nummern-Feld muss ausgefüllt sein.',
	),
	'clickatell_password' => array(
		'length' => 'Das Clickatell-Passwort-Feld muss zwischen 5 und 50 Zeichen beinhalten.',
		'required' => 'Das Clickatell-Passwort-Feld muss ausgefüllt sein.',
	),
	'clickatell_username' => array(
		'length' => 'Das Clickatell-Nutzernamen-Feld darf nicht mehr als 50 Zeichen beinhalten.',
		'required' => 'Das Clickatell-Nutzernamen-Feld muss ausgefüllt sein.',
	),
	'configure_map' => 'Konfiguriere Karte',
	'default_location' => 'Standardposition',
	'default_map_all' => array(
		'alpha_numeric' => 'Das Farben-Feed-Feld scheint keinen gültigen Wert zu beinhalten?',
		'length' => 'Das Farbfeld darf nicht mehr als 6 Zeichen beinhalten.',
		'required' => 'Das Farbfeld muss ausgefüllt sein.',
	),
	'default_map_view' => 'Standard Kartenansicht',
	'default_zoom_level' => 'Standard Zoom Level',
	'download_city_list' => 'Empfange Städte von Geonames',
	'email_host' => array(
		'length' => 'Das Mail-Server-Port-Feld ist zu lang',
		'numeric' => 'Das Mail-Server-Port-Feld darf nur Nummern enthalten.',
	),
	'email_password' => array(
		'length' => 'Das Mail-Server-Passwort-Feld muss zwischen 5 und 50 Zeichen beinhalten.',
		'required' => 'Das Mail-Server-Passwort-Feld muss ausgefüllt sein.',
	),
	'email_port' => array(
		'length' => 'Das Mail-Server-Port-Feld ist zu lang',
		'numeric' => 'TDas Mail-Server-Port-Feld darf nur Nummern enthalten.',
	),
	'email_servertype' => array(
		'length' => 'Das Mail-Server-Port-Feld ist zu lang',
		'required' => 'Das Mail-Server-Port-Feld muss ausgefüllt sein.',
	),
	'email_username' => array(
		'length' => 'Das Mail-Server-Nutzernamen-Feld darf nicht mehr als 50 Zeichen beinhalten.',
		'required' => 'Das Mail-Server-Nutzernamen-Feld muss ausgefüllt sein.',
	),
	'facebook' => array(
		'title' => 'Facebook Einrichtungsoptionen',
		'description' => 'Um die untenstehenden Informatione zu erhalten, musst du eine neue Facebookanwendung erstellen unter',
		'app_id' => 'Facebook App ID',
		'app_secret' => 'Facebook App Secret',
	),
	'google_analytics' => array(
		'length' => 'Das Google Analytics Feld muss eine gültige Web Property ID im Format UA-XXXXX-XX beinhalten.',
	),
	'https' => array(
		'enable_https' => 'Aktiviere HTTPS',
		'https_disabled' => 'Mit dieser Option wird Ushahidi in unsicherem Modus erreichbar; <strong>ohne</strong> "https://" im URL Präfix',
		'https_enabled' => 'Mit dieser Option wird Ushahidi in sicherem Modus erreichbar; mit <strong>https</strong> im URL Präfix',
		'title' => 'HTTPS',
	),
	'items_per_page' => array(
		'between' => 'Das Einträge-pro-Seite-Feld (Frontend) scheint einen ungültigen Wert zu enthalten?',
		'required' => 'Das Einträge-pro-Seite-Feld (Frontend) muss ausgefüllt sein.',
	),
	'items_per_page_admin' => array(
		'between' => 'Das Einträge-pro-Seite-Feld (Admin) scheint einen ungültigen Wert zu enthalten?',
		'required' => 'Das Einträge-pro-Seite-Feld (Admin) muss ausgefüllt sein.',
	),
	'map' => array(
		'default_location' => 'Den Kartenanbieter einzurichten ist ein recht einfacher Vorgang. Wähle einen Anbieter, besorge dir einen API-Schlüssel von der Anbieterseite, und gib den API-Schlüssel ein',
		'zoom' => 'Zoom Level',
	),
	'map_provider' => array(
		'choose' => 'Wähle einen Kartenanbieter',
		'enter_api' => 'Eingabe des API-Schlüssel',
		'get_api' => 'Fordere einen API-Schlüssel an',
		'info' => 'Den Kartenanbieter einzurichten ist ein recht einfacher Vorgang. Wähle einen Anbieter, besorge dir einen API-Schlüssel von der Anbieterseite, und gib den API-Schlüssel ein',
		'name' => 'Kartenanbieter',
	),
	'map_settings' => 'Karten Einstellungen',
	'multiple_countries' => 'Überspannt diese Ushahidi-Instanz mehrer Länder',
	'select_default_location' => 'Bitte wähle ein Standardland',
	'set_location' => 'Klicke auf die Karte um deine exakte Position zu setzen.',
	'site' => array(
		'allow_clustering' => 'Gruppiere Berichte auf Karte',
		'allow_comments' => 'Erlaube Nutzern Kommentare zu Berichten zu schreiben',
		'allow_feed' => 'RSS News Feed auf Webseite einbinden',
		'allow_reports' => 'Erlaube Nutzern Meldungen zu erzeugen.',
		'api_akismet' => 'Akismet-Schlüssel',
		'cache_pages' => 'Cache Seiten',
		'cache_pages_lifetime' => 'Seitencache Lebenszeit',
		'copyright_statement' => 'Copyright Statement',
		'default_category_colors' => 'Standardfarbe für alle Kategorien',
		'display_contact_page' => 'Zeige Kontaktseite',
		'display_howtohelp_page' => 'Zeige "Hilfe" Seite',
		'email_alerts' => 'Email-Adresse für Meldungen',
		'email_notice' => '<span>Zum Empfangen von Mails müssen die Email-Einstellungen konfiguriert werden.</span>',
		'email_site' => 'Emailadresse der Seite',
		'google_analytics' => 'Google Analytics',
		'google_analytics_example' => 'Web Property ID - Format: UA-XXXXX-XX',
		'items_per_page' => 'Einträge pro Seite - Front End',
		'items_per_page_admin' => 'Einträge pro Seite - Admin',
		'kismet_notice' => 'Kommentarspam verhindern durch Benutzung von <a href="http://akismet.com/" target="_blank">Akismet</a> von Automattic. <BR />Du kannst einen kostenlosen API-Schlüssel erhalten, wenn du dich für ein <a href="http://en.wordpress.com/api-keys/" target="_blank">WordPress.com Konto</a> registrierst',
		'laconica_configuration' => 'Laconica Credentials',
		'laconica_site' => 'Laconica Site ',
		'language' => 'Sprache der Seite',
		'message' => 'Seitennachricht',
		'name' => 'Seitenname',
		'share_site_stats' => 'Seitenstatistiken über API teilen',
		'tagline' => 'Seitenuntertitel',
		'title' => 'Seiteneinstellungen',
		'twitter_configuration' => 'Twitter Credentials',
		'twitter_hashtags' => 'Hashtags - trennen durch Kommas ',
	),
	'site_email' => array(
		'email' => 'Das Seiten-eMail-Adressen-Feld scheint eine ungültige eMail-Adresse zu enthalten?',
		'length' => 'Das Seiten-eMail-Adressen-Feld muss zwischen 4 und 100 Zeichen beinhalten.',
	),
	'site_name' => array(
		'length' => 'Das Seitenname-Feld muss zwischen 3 und 50 Zeichen beinhalten.',
		'required' => 'Das Seitenname-Feld muss ausgefüllt sein.',
	),
	'site_tagline' => array(
		'length' => 'Das Untertitel-Feld muss zwischen 3 und 100 Zeichen beinhalten.',
		'required' => 'Das Untertitel-Feld muss ausgefüllt sein.',
	),
	'sms' => array(
		'clickatell_api' => 'Deine Clickatell API Nummer',
		'clickatell_check_balance' => 'Checke dein Clickatell-Guthaben',
		'clickatell_load_balance' => 'Lade Guthaben',
		'clickatell_password' => 'Dein Clickatell Passwort',
		'clickatell_text_1' => '<a href="https://www.clickatell.com/central/user/client/step1.php?prod_id=2" target="_blank">Hier klicken</a>, um sich für den Clickatell-Service anzumelden',
		'clickatell_text_2' => 'Gib deine Clickatell-Zugangsdaten ein.',
		'clickatell_username' => 'Dein Clickatell-Benutzername',
		'flsms_description' => 'FrontlineSMS ist freie, quelloffene Software, die einen Laptop und ein Mobiltelefon in einen zentralen Kommunikationsknotenpunkt verwandelt. Einmal installiert ermöglicht das Programm Benutzern das Senden und Empfangen von Textnachrichten über Mobiltelefone an große Gruppen von Menschen. Klicke auf die graue Box um den Download von FrontlineSMS.com anzufordern.',
		'flsms_download' => 'Downloade Frontline SMS und installiere es auf Deinem PC',
		'flsms_instructions' => 'Nachrichten, die in einem FrontlineSMS empfangen werden, können mit Ushahidi synchronisiert werden. Detaillierte Anweisungen findest du auf <strong><a href="http://wiki.ushahididev.com/doku.php?id=how_to_use_ushahidi_alpha#how_to_setup_frontlinesms_to_sync_with_ushahidi" target="_blank">hier</a></strong>. Du brauchst untenstehenden Schlüssel und Link um die Synchronisation mit FrontlineSMS einzurichten',
		'flsms_key' => 'Dein Ushahidi-Sync-Schlüssel',
		'flsms_link' => 'FrontlineSMS HTTP Post LINK',
		'flsms_synchronize' => 'Synchronisiere mit Ushahidi',
		'flsms_text_1' => 'Gib die Telefonnummer für die Verbindung zu Frontline SMS ein.',
		'flsms_text_2' => 'Gib die Nummer ohne + oder Striche ein.',
		'option_1' => 'Option 1: Nutze Frontline SMS',
		'option_2' => 'Option 2: Nutze ein globales SMS Gateway',
		'title' => 'SMS Einrichtungsoptionen',
	),
	'sms_no1' => array(
		'length' => 'Die Eingabe in Telefonfeld 1 ist ungültig.',
		'numeric' => 'Das Telefonfeld 1 sollte nur Nummern enthalten.',
	),
	'sms_no2' => array(
		'length' => 'Die Eingabe in Telefonfeld 2 ist zu lang.',
		'numeric' => 'Das Telefonfeld 2 sollte nur Nummern enthalten.',
	),
	'sms_no3' => array(
		'length' => 'Die Eingabe in Telefonfeld 3 ist zu lang.',
		'numeric' => 'Das Telefonfeld darf nur Nummern enthalten',
	),
	'sms_provider' => array(
		'length' => 'SMS-Anbieter',
	));
?>
