<?php
	$lang = array(
	'allow_comments' => array(
		'between' => 'Das Kommentare-erlauben-Feld scheint einen ungültigen Wert zu enthalten?',
		'required' => 'Das Kommentare-erlauben-Feld muss ausgefüllt sein.',
	),
	'allow_feed' => array(
		'between' => 'Das Feed-einbinden-Feld scheint einen ungültigen Wert zu enthalten?',
		'required' => 'The Feed-einbinden-Feld muss ausgefüllt sein.',
	),
	'allow_reports' => array(
		'between' => 'Das Berichte-erlauben-Feld scheint einen ungültigen Wert zu enthalten?',
		'required' => 'Das Berichte-erlauben-Feld muss ausgefüllt sein.',
	),
	'allow_stat_sharing' => array(
		'between' => 'Das stat-sharing-Feld scheint einen ungültigen Wert zu enthalten?',
		'required' => 'Das stat-sharing-Feld muss ausgefüllt sein.',
	),
	'api' => array(
		'default_record_limit' => 'Standardanzahl von Einträgen der API-Anforderung',
		'maximum_record_limit' => 'Maximale Anzahl an Einträgen die pro API-Anfrage geholt werden.',
		'maximum_requests_per_ip_address' => 'Maximale Anzahl an API-Anfragen pro IP-Adresse',
	),
	'api_akismet' => array(
		'alpha_numeric' => 'Das Akismet-Feld scheint einen ungültigen Wert zu enthalten?',
		'length' => 'Das Akismet-Feld scheint einen ungültigen Wert zu enthalten?',
	),
	'banner_image' => array(
		'default' => 'Es ist ein Fehler aufgetreten beim Upload deines Bannerbildes.',
		'size' => 'Die Größe deines Banners übertrifft das Größenlimit für diesen Upload.',	
	),
	'api_default_record_limit' => 'Standard API Grenze',
	'cache_pages' => array(
		'between' => 'Das Cache-Feld muss ausgefüllt sein.',
		'required' => 'Das Cache-Feld enthält einen ungültigen Wert',
	),
	'cache_pages_lifetime' => array(
		'in_array' => 'Das Cache-Feld enthält einen ungültigen Wert',
		'required' => 'Das Cache-Feld muss ausgefüllt sein.',
	),
	'cleanurl' => array(
		'clean_url_disabled' => 'It looks like your server is not configured to handle clean URLs. You will need to change the configuration of your server before you can enable clean URLs. See more info on how to enable clean URLs at this forum <a href="http://forums.ushahidi.com/topic/server-configuration-for-apache-mod-rewrite" target="_blank">post</a>',
		'clean_url_enabled' => 'This option makes Ushahidi to be accessed via "clean" URLs. Without "index.php" in the URL.',
		'enable_clean_url' => 'Enable Clean URLs',
		'title' => 'Clean URLs',
	),
	'clickatell_api' => array(
		'length' => 'The Clickatell API number field must be no more 20 characters long.',
		'required' => 'The Clickatell API number field muss ausgefüllt sein.',
	),
	'clickatell_password' => array(
		'length' => 'The Clickatell Password field must be at least 5 and no more 50 characters long.',
		'required' => 'The Clickatell Password field muss ausgefüllt sein.',
	),
	'clickatell_username' => array(
		'length' => 'The Clickatell Username field must be no more 50 characters long.',
		'required' => 'The Clickatell Username field muss ausgefüllt sein.',
	),
	'configure_map' => 'Konfiguriere Karte',
	'default_location' => 'Standardposition',
	'default_map_all' => array(
		'alpha_numeric' => 'The color feed field does not appear to contain a valid value?',
		'length' => 'The color field must be no more 6 characters long.',
		'required' => 'The color field is required.',
	),
	'default_map_view' => 'Standard Map View',
	'default_zoom_level' => 'Standard Zoom Level',
	'download_city_list' => 'Empfange Staedte von Geonames',
	'email_host' => array(
		'length' => 'The Mail server port field is too long',
		'numeric' => 'The Mail server port field should contain numbers only.',
	),
	'email_password' => array(
		'length' => 'The Mail Server Password field must be at least 5 and no more 50 characters long.',
		'required' => 'The Mail Server Password field muss ausgefüllt sein.',
	),
	'email_port' => array(
		'length' => 'The Mail server port field is too long',
		'numeric' => 'The Mail server port field should contain numbers only.',
	),
	'email_servertype' => array(
		'length' => 'The Mail server port field is too long',
		'required' => 'The Mail Server Type field muss ausgefüllt sein.',
	),
	'email_username' => array(
		'length' => 'The Mail Server Username field must be no more 50 characters long.',
		'required' => 'The Mail Server Username field muss ausgefüllt sein.',
	),
	'facebook' => array(
		'title' => 'Facebook Setup Options',
		'description' => 'To get the information below you will need to create a new Facebook application at',
		'app_id' => 'Facebook App ID',
		'app_secret' => 'Facebook App Secret',
	),
	'google_analytics' => array(
		'length' => 'Das Google Analytics Feld muss eine gültige Web Property ID im Format UA-XXXXX-XX beinhalten.',
	),
	'https' => array(
		'enable_https' => 'Aktiviere HTTPS',
		'https_disabled' => 'This option makes Ushahidi be accessed in unsecure mode; <strong>without</strong> "https://" in the URL prefix',
		'https_enabled' => 'This option makes Ushahidi be accessed in secure mode; with <strong>https</strong> in the URL prefix',
		'title' => 'HTTPS',
	),
	'items_per_page' => array(
		'between' => 'The items per page (Frontend) field does not appear to contain a valid value?',
		'required' => 'The items per page (Frontend) field muss ausgefüllt sein.',
	),
	'items_per_page_admin' => array(
		'between' => 'The items per page (Admin) field does not appear to contain a valid value?',
		'required' => 'The items per page (Admin) field muss ausgefüllt sein.',
	),
	'map' => array(
		'default_location' => 'Setting up your map provider is a straight- forward process. Select a provider, obtain an API key from the provider\'s site, and enter the API key',
		'zoom' => 'Zoom Level',
	),
	'map_provider' => array(
		'choose' => 'Wählen Sie einen Kartenanbieter',
		'enter_api' => 'Eingabe des API Key',
		'get_api' => 'Fordern Sie einen API Key an',
		'info' => 'Setting up your map provider is a straight- forward process. Select a provider, obtain an API key from the provider\'s site, and enter the API key',
		'name' => 'Kartenanbieter',
	),
	'map_settings' => 'Karten Einstellungen',
	'multiple_countries' => 'Does this Ushahidi Deployment Span Multiple Countries',
	'select_default_location' => 'Bitte wählen sie ihr Standardland',
	'set_location' => 'Klicken Sie auf die Karte um Ihre exakte Position zu setzen.',
	'site' => array(
		'allow_clustering' => 'Cluster Reports auf Karte',
		'allow_comments' => 'Allow Users to Submit Comments to Reports',
		'allow_feed' => 'Include RSS News Feed on Website',
		'allow_reports' => 'Erlaube Nutzern Meldungen zu erzeugen.',
		'api_akismet' => 'Akismet Schlüssel',
		'cache_pages' => 'Cache Seiten',
		'cache_pages_lifetime' => 'Seitencache Lebenszeit',
		'copyright_statement' => 'Copyright Statement',
		'default_category_colors' => 'Standardfarbe für alle Kategorien',
		'display_contact_page' => 'Zeige Kontaktseite',
		'display_howtohelp_page' => 'Zeige "Hilfe" Seite',
		'email_alerts' => 'Email Addresse fuer Alarme',
		'email_notice' => '<span>Zum empfangen von Mails muessen Sie Ihre Email-Einstellungen konfigurieren.</span>',
		'email_site' => 'Seite Emailaddresse',
		'google_analytics' => 'Google Analytics',
		'google_analytics_example' => 'Web Property ID - Format: UA-XXXXX-XX',
		'items_per_page' => 'Eintraege pro Seite - Front End',
		'items_per_page_admin' => 'Eintraege pro Seite - Admin',
		'kismet_notice' => 'Prevent comment spam using <a href="http://akismet.com/" target="_blank">Akismet</a> from Automattic. <BR />You can get a free API key by registering for a <a href="http://en.wordpress.com/api-keys/" target="_blank">WordPress.com user account</a>',
		'laconica_configuration' => 'Laconica Credentials',
		'laconica_site' => 'Laconica Site ',
		'language' => 'Sprache der Seite',
		'message' => 'Seiten Nachricht',
		'name' => 'Seitenname',
		'share_site_stats' => 'Share Site Statistics in API',
		'tagline' => 'Seiten Untertitel',
		'title' => 'Seiteneinstellungen',
		'twitter_configuration' => 'Twitter Credentials',
		'twitter_hashtags' => 'Hashtags - trennen durch Kommas ',
	),
	'site_email' => array(
		'email' => 'The site email field does not appear to contain a valid email address?',
		'length' => 'The site email field must be at least 4 and no more 100 characters long.',
	),
	'site_name' => array(
		'length' => 'The site name field must be at least 3 and no more 50 characters long.',
		'required' => 'The site name field muss ausgefüllt sein.',
	),
	'site_tagline' => array(
		'length' => 'The tagline field must be at least 3 and no more 100 characters long.',
		'required' => 'The tagline field muss ausgefüllt sein.',
	),
	'sms' => array(
		'clickatell_api' => 'Ihre Clickatell API Nummer',
		'clickatell_check_balance' => 'Checken Sie Ihr Clickatell Buthaben',
		'clickatell_load_balance' => 'Lade Guthaben',
		'clickatell_password' => 'Ihr Clickatell Passwort',
		'clickatell_text_1' => 'Sign up for Clickatells service by <a href="https://www.clickatell.com/central/user/client/step1.php?prod_id=2" target="_blank">clicking here</a>',
		'clickatell_text_2' => 'Geben Sie Ihre Clickatell Zugangsdaten ein.',
		'clickatell_username' => 'Ihr Clickatell Benutzername',
		'flsms_description' => 'FrontlineSMS ist freie, quelloffene Software, die einen Laptop und ein Mobiltelefon in einen zentralen Kommunikationsknotenpunkt verwandelt. Einmal installiert ermöglicht das Programm Benutzern das Senden und Empfangen von Textnachrichten über Mobiltelefone an große Gruppen von Menschen. Klicke auf die graue Box um den Download von FrontlineSMS.com anzufordern.',
		'flsms_download' => 'Downloade Frontline SMS und installiere es auf Deinem PC',
		'flsms_instructions' => 'Nachrichten, die in einem FrontlineSMS empfangen werden, können mit Ushahidi synchronisiert werden. Detaillierte Anweisungen findest Du auf <strong><a href="http://wiki.ushahididev.com/doku.php?id=how_to_use_ushahidi_alpha#how_to_setup_frontlinesms_to_sync_with_ushahidi" target="_blank">here</a></strong>. You will require the key and link below to set up the sync with FrontlineSMS',
		'flsms_key' => 'Ihr Ushahidi Sync Key',
		'flsms_link' => 'FrontlineSMS HTTP Post LINK',
		'flsms_synchronize' => 'Synchronisiere mit Ushahidi',
		'flsms_text_1' => 'Geben Sie die Telefonnummer für die Verbindung zu Frontline SMS ein.',
		'flsms_text_2' => 'Geben Sie die Nummer ohne + oder Striche ein.',
		'option_1' => 'Option 1: Nutze Frontline SMS',
		'option_2' => 'Option 2: Nutze ein globales SMS Gateway',
		'title' => 'SMS Setup Optionen',
	),
	'sms_no1' => array(
		'length' => 'Die Eingabe in Telefonfeld 1 ist ungültig.',
		'numeric' => 'Das Telefonfeld 1 sollte nur Nummern enthalten.',
	),
	'sms_no2' => array(
		'length' => 'Die Eingabe in Telefonfeld 2 ist zu lang.',
		'numeric' => 'Das Telefonfeld 2 sollte nur Nummern enthalten.',
	),
	'sms_no3' => array(
		'length' => 'Die Eingabe in Telefonfeld 3 ist zu lang.',
		'numeric' => 'Das Telefonfeld darf nur Nummern enthalten',
	),
	'sms_provider' => array(
		'length' => 'SMS-Provider',
	));
?>
